name: plant_detector
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts:
  flutter_riverpod:
  camera:
  google_generative_ai:
  path_provider:
  shared_preferences:
  image_cropper:
  flutter_markdown:
  fl_chart:
  url_launcher:
  share_plus:
  in_app_purchase:



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

